name: 'Show Line Diff'
description: 'Displays the line differences between HEAD and a given commit hash'
author: 'ILikePlayingGames'
branding:
  icon: git-pull-request
  color: red
inputs:
  commit-hash:
    required: true
    description: 'The commit hash to compare to HEAD, or `second-commit-hash` if provided'
  second-commit-hash:
    required: false
    default: '@'
    description: 'The commit hash to compare the first commit hash to, defaults to HEAD'
  diff-algorithm:
    required: false
    description: 'The git diff algorithm to use'
  column-width:
    required: false
    default: '80'
    description: 'The column width of the resulting formatted diff, defaults to 80'
  ruler-width:
    required: false
    description: 'The width of the horizontal line below the formatted file title, defaults to `column-width`'
outputs:
  diff:
    description: 'The formatted line differences between HEAD and a given commit hash'
runs:
  using: 'node16'
  main: 'dist/index.js'
