name: 'Show Line Diff'
description: 'Displays the line differences between HEAD and a given commit hash'
author: 'ILikePlayingGames'
branding:
  icon: git-pull-request
  color: red
inputs:
  commit-hash: # change this
    required: true
    description: 'The commit hash to compare to HEAD'
outputs:
  diff:
    description: 'The formatted line differences between HEAD and a given commit hash'
runs:
  using: 'node16'
  main: 'dist/index.js'
