name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**.yml'
  push:
    branches-ignore:
      - main
      - 'releases/*'
    paths-ignore:
      - '**.md'
      - '.github/**.yml'
  workflow-dispatch:

jobs:
  rapid-test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: run_action
        uses: ./
        with:
          commit-hash: '@~'
