name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**.yml'
      - '.github/workflows/**.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**.yml'
      - '.github/workflows/**.yml'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          npm install
      - run: |
          npm run build
  test-ubuntu: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: run_action
        uses: ./
        with:
          commit-hash: '@~'
      - name: Ensure output is set correctly.
        run: cat $HOME/diff.txt
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: run_action
        uses: ./
        with:
          commit-hash: '@~'
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: run_action
        uses: ./
        with:
          commit-hash: '@~'
